### ISSUE TITLE
Errors on molecules and calculations pages

### ISSUE THREAD

**Issue by psavery** [OpenChemistry/oc-web-components#121]
Hi all, 

As of the latest changes to our all of our repos (mongochemserver, openchemistrypy, mongochemdeploy, mongochemclient, and this one), I started getting some javascript errors on the cards pages for molecules and calculations, and no cards appear on either page. This happens in ocdeploy with all of the default images and settings. The errors are attached below, and appear to be related to oc-web-components.

However, I don't have any issues if I use my local install of mongochemclient with all of the default node modules. Maybe we just need to update the node modules in the docker image or something?

[calculations_errors.log](https://github.com/OpenChemistry/oc-web-components/files/3283263/calculations_errors.log)
[molecules_errors.log](https://github.com/OpenChemistry/oc-web-components/files/3283264/molecules_errors.log)

**Comment by cjh1** [comment]
@psavery I have fixed a build issue with the mongochemclient container. Can you pull the latest container and try again?

**Comment by psavery** [comment]
Unfortunately, it looks like the container still has the issue. Maybe it hasn't been re-built yet.

**Comment by psavery** [comment]
Do I need to do anything special to update the nginx container? I still get the same issue, even after `docker pull openchemistry/mongochemserver` and `ocdeploy pull` for the latest master branch of mongochemdeploy.

![image](https://user-images.githubusercontent.com/9558430/59847142-b15e3d00-932f-11e9-9730-ec982248e50c.png)
